### ISSUE TITLE
Allow event details to be added to the message

### ISSUE THREAD

**Issue by apothan** [s3krit/Matrix-Message#2]
At the moment the message just seems to allow a static message. It would be nice to be able to add the commit hash, commit message and commit user to the message.

If there is a simple way to do this with this library maybe we can add it to the README.md

**Comment by s3krit** [comment]
The message defined by the action can include any variables exposed by Github Actions. For instance, anything in the [Events API](https://developer.github.com/v3/activity/events/). I've used this for including useful information when publishing releases (which was what prompted me to write this action), and you can see that in action [here](https://github.com/paritytech/polkadot/blob/master/.github/workflows/release-bot.yml#L15).

Hope that helps!
